## This configuration was generated by terraform-provider-oci

resource oci_core_nat_gateway export_NAT-Gateway-nebula {
  block_traffic  = "false"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "steve.j.gore@gmail.com"
    "Oracle-Tags.CreatedOn" = "2021-02-04T09:31:21.475Z"
  }
  display_name = "NAT Gateway-nebula"
  freeform_tags = {
    "VCN" = "VCN-2021-02-04T09:30:36"
  }
  public_ip_id = "ocid1.publicip.oc1.ap-sydney-1.aaaaaaaaiaipczqhtkitgbhihdt6l2mwkciu6m6pzpkyelum2yml3aoc6ndq"
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_nebula.id
}


resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-nebula {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "steve.j.gore@gmail.com"
    "Oracle-Tags.CreatedOn" = "2021-02-04T09:31:20.993Z"
  }
  display_name     = "Default DHCP Options for nebula"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
    "VCN" = "VCN-2021-02-04T09:30:36"
  }
  manage_default_resource_id = "ocid1.dhcpoptions.oc1.ap-sydney-1.aaaaaaaafnkriy5d33vdmksnlldav4sjhvsidr54zpw4hf67zhsjkphzwxaq"
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "nebula.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_internet_gateway export_Internet-Gateway-nebula {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "steve.j.gore@gmail.com"
    "Oracle-Tags.CreatedOn" = "2021-02-04T09:31:21.488Z"
  }
  display_name = "Internet Gateway-nebula"
  enabled      = "true"
  freeform_tags = {
    "VCN" = "VCN-2021-02-04T09:30:36"
  }
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_nebula.id
}

resource oci_core_subnet export_Private-Subnet-nebula {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.1.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "steve.j.gore@gmail.com"
    "Oracle-Tags.CreatedOn" = "2021-02-04T09:31:30.501Z"
  }
  dhcp_options_id = oci_core_default_dhcp_options.export_Default-DHCP-Options-for-nebula.id
  display_name    = "Private Subnet-nebula"
  dns_label       = "sub02040931041"
  freeform_tags = {
    "VCN" = "VCN-2021-02-04T09:30:36"
  }
  ipv4cidr_blocks = [
    "10.0.1.0/24",
  ]
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_Route-Table-for-Private-Subnet-nebula.id
  security_list_ids = [
    oci_core_security_list.export_nebula-private.id,
  ]
  vcn_id = oci_core_vcn.export_nebula.id
}

resource oci_core_subnet export_Public-Subnet-nebula {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.0.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "steve.j.gore@gmail.com"
    "Oracle-Tags.CreatedOn" = "2021-02-04T09:31:21.440Z"
  }
  dhcp_options_id = oci_core_default_dhcp_options.export_Default-DHCP-Options-for-nebula.id
  display_name    = "Public Subnet-nebula"
  dns_label       = "sub02040931040"
  freeform_tags = {
    "VCN" = "VCN-2021-02-04T09:30:36"
  }
  ipv4cidr_blocks = [
    "10.0.0.0/24",
  ]
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_nebula.default_route_table_id
  security_list_ids = [
    oci_core_default_security_list.export_nebula-public.id,
  ]
  vcn_id = oci_core_vcn.export_nebula.id
}

resource oci_core_security_list export_nebula-private {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "steve.j.gore@gmail.com"
    "Oracle-Tags.CreatedOn" = "2021-02-04T09:31:21.687Z"
  }
  display_name = "nebula-private"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "VCN" = "VCN-2021-02-04T09:30:36"
  }
  ingress_security_rules {
    description = "SSH from VCN"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "ICMP from VCN"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  # MySQL HeatWave Free DB endpoint — workers in the same Private Subnet
  # connect on 3306 (classic) and 33060 (X protocol). NSG-based isolation
  # would be tighter but the OCI MySQL service rejects any nsg_ids attached
  # at create time with "AuthorizationFailed", even with the documented
  # `manage virtual-network-family` policy. SL-based allow from the Private
  # Subnet CIDR (10.0.1.0/24) is functionally equivalent here since the
  # subnet only holds OKE workers.
  ingress_security_rules {
    description = "MySQL classic protocol from Private Subnet"
    protocol    = "6"
    source      = "10.0.1.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      min = "3306"
      max = "3306"
    }
  }
  ingress_security_rules {
    description = "MySQL X protocol from Private Subnet"
    protocol    = "6"
    source      = "10.0.1.0/24"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      min = "33060"
      max = "33060"
    }
  }
  vcn_id = oci_core_vcn.export_nebula.id

  # OCI CCM injects NodePort ingress rules here when LoadBalancer-type
  # Services are reconciled. Don't fight it — TF owns the static rules
  # declared above, the CCM owns the dynamic per-Service rules.
  lifecycle {
    ignore_changes = [ingress_security_rules, egress_security_rules]
  }
}

resource oci_core_default_security_list export_nebula-public {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "steve.j.gore@gmail.com"
    "Oracle-Tags.CreatedOn" = "2021-02-04T09:31:20.993Z"
  }
  display_name = "nebula-public"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "VCN" = "VCN-2021-02-04T09:30:36"
  }
  ingress_security_rules {
    description = "ICMP Path MTU Discovery"
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "ICMP from VCN"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "SSH from home IP"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "159.196.97.38/32"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "HTTP"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "80"
      min = "80"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "HTTPS"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "443"
      min = "443"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "Plex"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "32400"
      min = "32400"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    description = "WireGuard"
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "17"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    udp_options {
      max = "51820"
      min = "51820"
      #source_port_range = <<Optional value not found in discovery>>
    }
  }
  manage_default_resource_id = "ocid1.securitylist.oc1.ap-sydney-1.aaaaaaaasjcn3v53u7bsh63nzzuo4zl7jgv25pcx2ziamb6e2rvnyrbjicvq"

  # OCI CCM injects NodePort egress rules here when the NLB in this subnet
  # backends to k8s NodePorts on the private subnet. Same TF/CCM split as
  # nebula-private.
  lifecycle {
    ignore_changes = [ingress_security_rules, egress_security_rules]
  }
}

resource oci_core_vcn export_nebula {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "steve.j.gore@gmail.com"
    "Oracle-Tags.CreatedOn" = "2021-02-04T09:31:20.993Z"
  }
  display_name = "nebula"
  dns_label    = "nebula"
  freeform_tags = {
    "VCN" = "VCN-2021-02-04T09:30:36"
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
  security_attributes = {
  }
}

resource oci_core_service_gateway export_Service-Gateway-nebula {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "steve.j.gore@gmail.com"
    "Oracle-Tags.CreatedOn" = "2021-02-04T09:31:21.582Z"
  }
  display_name = "Service Gateway-nebula"
  freeform_tags = {
    "VCN" = "VCN-2021-02-04T09:30:36"
  }
  #route_table_id = <<Optional value not found in discovery>>
  services {
    service_id = "ocid1.service.oc1.ap-sydney-1.aaaaaaaaar6xfo4rtfjgv2mmjvo7u77zyr4uyqkc764f2t2jxwwayrjhsjyq"
  }
  vcn_id = oci_core_vcn.export_nebula.id
}

resource oci_core_route_table export_Route-Table-for-Private-Subnet-nebula {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "steve.j.gore@gmail.com"
    "Oracle-Tags.CreatedOn" = "2021-02-04T09:31:21.523Z"
  }
  display_name = "Route Table for Private Subnet-nebula"
  freeform_tags = {
    "VCN" = "VCN-2021-02-04T09:30:36"
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_nat_gateway.export_NAT-Gateway-nebula.id
    route_type        = "STATIC"
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "all-syd-services-in-oracle-services-network"
    destination_type  = "SERVICE_CIDR_BLOCK"
    network_entity_id = oci_core_service_gateway.export_Service-Gateway-nebula.id
    route_type        = "STATIC"
  }
  vcn_id = oci_core_vcn.export_nebula.id
}

resource oci_core_default_route_table export_Default-Route-Table-for-nebula {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "steve.j.gore@gmail.com"
    "Oracle-Tags.CreatedOn" = "2021-02-04T09:31:20.993Z"
  }
  display_name = "Default Route Table for nebula"
  freeform_tags = {
    "VCN" = "VCN-2021-02-04T09:30:36"
  }
  manage_default_resource_id = oci_core_vcn.export_nebula.default_route_table_id
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_Internet-Gateway-nebula.id
    route_type        = "STATIC"
  }
}

