## This configuration was generated by terraform-provider-oci

resource oci_identity_compartment export_main {
  compartment_id = var.tenancy_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "steve.j.gore@gmail.com"
    "Oracle-Tags.CreatedOn" = "2021-02-04T09:07:52.533Z"
  }
  description = "Main compartment for compute and networking resources"
  #enable_delete = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  name = "main"
}







resource oci_identity_policy export_vault-kms-objectstorage-policy {
  compartment_id = oci_identity_compartment.export_main.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/steve.j.gore@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-01-28T09:52:07.254Z"
  }
  description = "Allow vault-instances to use KMS and Object Storage"
  freeform_tags = {
  }
  name = "vault-kms-objectstorage-policy"
  statements = [
    "Allow dynamic-group vault-instances to use keys in compartment main",
    "Allow dynamic-group vault-instances to manage objects in compartment main where target.bucket.name='vault-storage'",
    "Allow dynamic-group vault-instances to manage objects in compartment main where target.bucket.name='caddy-acme'",
    "Allow dynamic-group vault-instances to read buckets in compartment main",
  ]
}




resource oci_identity_dynamic_group export_vault-instances {
  compartment_id = var.tenancy_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/steve.j.gore@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-01-28T09:51:51.727Z"
  }
  description = "Instances allowed to use KMS + Object Storage for the Vault unseal flow. Was scoped to the ampere instance OCID until 2026-05-25; broadened to compartment-match so future OKE worker instances pick up the same auth."
  freeform_tags = {
  }
  name          = "vault-instances"
  matching_rule = "instance.compartment.id = '${var.compartment_ocid}'"
}













