## This configuration was generated by terraform-provider-oci

resource oci_kms_vault export_hashicorp-vault-unseal {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/steve.j.gore@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-01-28T09:46:47.122Z"
  }
  display_name = "hashicorp-vault-unseal"
  #external_key_manager_metadata = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  #restore_from_file = <<Optional value not found in discovery>>
  #restore_from_object_store = <<Optional value not found in discovery>>
  #restore_trigger = <<Optional value not found in discovery>>
  #time_of_deletion = <<Optional value not found in discovery>>
  vault_type = "DEFAULT"
}

resource oci_kms_key export_vault-auto-unseal {
  #auto_key_rotation_details = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/steve.j.gore@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-01-28T09:48:24.566Z"
  }
  desired_state = "ENABLED"
  display_name  = "vault-auto-unseal"
  #external_key_reference = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  is_auto_rotation_enabled = "false"
  key_shape {
    algorithm = "AES"
    curve_id  = ""
    length    = "32"
  }
  management_endpoint = "https://fnuxtwyhaahla-management.kms.ap-sydney-1.oraclecloud.com"
  protection_mode     = "HSM"
  #restore_from_file = <<Optional value not found in discovery>>
  #restore_from_object_store = <<Optional value not found in discovery>>
  #restore_trigger = <<Optional value not found in discovery>>
  #time_of_deletion = <<Optional value not found in discovery>>
}

resource oci_kms_key_version export_vault-auto-unseal_key_version {
  #external_key_version_id = <<Optional value not found in discovery>>
  key_id              = "ocid1.key.oc1.ap-sydney-1.fnuxtwyhaahla.abzxsljrgzjola7olf2nj27fljzgkqx5vdwq5f44g7n6wse3awmsoee2imfa"
  management_endpoint = "https://fnuxtwyhaahla-management.kms.ap-sydney-1.oraclecloud.com"
  #time_of_deletion = <<Optional value not found in discovery>>
}

