## This configuration was generated by terraform-provider-oci

resource "oci_kms_vault" "export_hashicorp-vault-unseal" {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/steve.j.gore@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-01-28T09:46:47.122Z"
  }
  display_name = "hashicorp-vault-unseal"
  #external_key_manager_metadata = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  #restore_from_file = <<Optional value not found in discovery>>
  #restore_from_object_store = <<Optional value not found in discovery>>
  #restore_trigger = <<Optional value not found in discovery>>
  #time_of_deletion = <<Optional value not found in discovery>>
  vault_type = "DEFAULT"

  # This vault holds the key that decrypts Vault's master key. Losing it makes
  # every object in the vault-storage bucket permanently undecryptable — the
  # recovery shares do NOT help, they only re-root a Vault that can already
  # unseal itself. Nothing else in this config is unrecoverable, so this one
  # gets a hard stop against `terraform destroy` and against any plan that
  # wants to replace it in place. If you genuinely need to remove it, delete
  # this block in a dedicated commit so the intent is on the record.
  lifecycle {
    prevent_destroy = true
  }
}

resource "oci_kms_key" "export_vault-auto-unseal" {
  #auto_key_rotation_details = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/steve.j.gore@gmail.com"
    "Oracle-Tags.CreatedOn" = "2026-01-28T09:48:24.566Z"
  }
  desired_state = "ENABLED"
  display_name  = "vault-auto-unseal"
  #external_key_reference = <<Optional value not found in discovery>>
  freeform_tags = {
  }
  is_auto_rotation_enabled = "false"
  key_shape {
    algorithm = "AES"
    curve_id  = ""
    length    = "32"
  }
  management_endpoint = "https://fnuxtwyhaahla-management.kms.ap-sydney-1.oraclecloud.com"
  protection_mode     = "HSM"
  #restore_from_file = <<Optional value not found in discovery>>
  #restore_from_object_store = <<Optional value not found in discovery>>
  #restore_trigger = <<Optional value not found in discovery>>
  #time_of_deletion = <<Optional value not found in discovery>>

  # The actual unseal key — see the note on oci_kms_vault above. HSM protection
  # means the raw material can never leave OCI, so there is no copy of this
  # anywhere else and no way to make one outside a `key backup` (which restores
  # only back into OCI). Treat destruction as data loss, not a rebuild.
  lifecycle {
    prevent_destroy = true
  }
}

resource "oci_kms_key_version" "export_vault-auto-unseal_key_version" {
  #external_key_version_id = <<Optional value not found in discovery>>
  key_id              = "ocid1.key.oc1.ap-sydney-1.fnuxtwyhaahla.abzxsljrgzjola7olf2nj27fljzgkqx5vdwq5f44g7n6wse3awmsoee2imfa"
  management_endpoint = "https://fnuxtwyhaahla-management.kms.ap-sydney-1.oraclecloud.com"
  #time_of_deletion = <<Optional value not found in discovery>>
}

