# Variables generated by ORM Resource Discovery and referenced by imported/*.tf.
# `compartment_ocid` and `region` were dropped here because they're declared in
# the root `variables.tf` (with values from `terraform.tfvars`). Everything
# below is leftover static defaults the discovery emitted as variables — fine
# to leave for now; they'll fold into resource bodies during the refactor pass.
variable "fault_domain--FAULT-DOMAIN-2" { default = "FAULT-DOMAIN-2" }
variable "availability_domain--tbGS-AP-SYDNEY-1-AD-1" { default = "tbGS:AP-SYDNEY-1-AD-1" }
