version: '3'
services:
 radarr:
  container_name: radarr
  restart: unless-stopped
  networks:
  - transmission_net
  ports:
   - 7878:7878
  volumes:
   - radarr-config:/config
   - /var/lib/transmission:/data
   - /srv/movies:/movies
  environment:
   - TZ=Australia/Sydney
  image: linuxserver/radarr:6.3.0@sha256:95ba0801df4d9d1d79d0d9a3849f656542497dab061d91b87ad4f53a71aff3ef # https://hub.docker.com/r/linuxserver/radarr/tags
 
 sonarr:
  container_name: sonarr
  restart: unless-stopped
  networks:
  - transmission_net
  ports:
   - 8989:8989
  volumes:
   - sonarr-config:/config
   - /var/lib/transmission:/data
   - /srv/tv:/tv
  environment:
   - TZ=Australia/Sydney
  image: linuxserver/sonarr:4.0.19@sha256:82172b363f9eddc02aca544f880a044f2ceb9aaf190bc87e4454e2f705eb91d0  # https://hub.docker.com/r/linuxserver/sonarr/tags
 
 jackett:
  container_name: jackett
  restart: unless-stopped
  networks:
  - transmission_net
  ports:
   - 9117:9117
  volumes:
   - jackett-config:/config
  environment:
   - TZ=Australia/Sydney
  image: linuxserver/jackett:0.24.2544@sha256:acfe6c0d20f52da3b88b9efdc241ad80b843b3bead526ddd82f20f5621b84064  # https://hub.docker.com/r/linuxserver/jackett/tags

 flaresolverr:
  container_name: flaresolverr
  restart: unless-stopped
  networks:
  - transmission_net
  ports:
   - 8191:8191
  environment:
   - LOG_LEVEL=info
   - LOG_HTML=false
   - CAPTCHA_SOLVER=none
   - TZ=Australia/Sydney
  image: ghcr.io/flaresolverr/flaresolverr:latest@sha256:c80ae007ce2ccdcd217a12426e4f039ef763ff90738c808d38810c3e59323767
 
volumes:
  radarr-config:
  sonarr-config:
  jackett-config:

networks:
  transmission_net:
    external: true
