version: '3'
services:
 radarr:
  container_name: radarr
  restart: unless-stopped
  networks:
  - transmission_net
  ports:
   - 7878:7878
  volumes:
   - radarr-config:/config
   - /var/lib/transmission:/data
   - /srv/movies:/movies
  environment:
   - TZ=Australia/Sydney
  image: linuxserver/radarr:6.3.0@sha256:119aaa4a4f7349bcd2a136c5373a0d7925b5479915c7dfe0c0ad352db2a6d438 # https://hub.docker.com/r/linuxserver/radarr/tags
 
 sonarr:
  container_name: sonarr
  restart: unless-stopped
  networks:
  - transmission_net
  ports:
   - 8989:8989
  volumes:
   - sonarr-config:/config
   - /var/lib/transmission:/data
   - /srv/tv:/tv
  environment:
   - TZ=Australia/Sydney
  image: linuxserver/sonarr:4.0.19@sha256:4d9df314875e1249ab7d6170c2b9b3dc1d8e6383f168ceb10dc9a5ad9b324739  # https://hub.docker.com/r/linuxserver/sonarr/tags
 
 jackett:
  container_name: jackett
  restart: unless-stopped
  networks:
  - transmission_net
  ports:
   - 9117:9117
  volumes:
   - jackett-config:/config
  environment:
   - TZ=Australia/Sydney
  image: linuxserver/jackett:0.24.2531@sha256:ef4b5b9f09d0c014f48c8e6999abb782b53b4cea8b170ca049c96046950c8524  # https://hub.docker.com/r/linuxserver/jackett/tags

 flaresolverr:
  container_name: flaresolverr
  restart: unless-stopped
  networks:
  - transmission_net
  ports:
   - 8191:8191
  environment:
   - LOG_LEVEL=info
   - LOG_HTML=false
   - CAPTCHA_SOLVER=none
   - TZ=Australia/Sydney
  image: ghcr.io/flaresolverr/flaresolverr:latest@sha256:139dfee1c6f89249c8d665d1333a42e8ec74ec0a86bc6bb1c8461e10d3a66a47
 
volumes:
  radarr-config:
  sonarr-config:
  jackett-config:

networks:
  transmission_net:
    external: true
