version: '3.5'

services:
  nuraspace:
    image: nuraspace  # Built manually and kept local currently due to credentials
    ports:
      - 8111:5000
    environment:
      TZ: Australia/Sydney
    restart: unless-stopped
    volumes:
      - /var/nura:/var/nura
      - /etc/localtime:/etc/localtime:ro
    
