services:
  icloudpdk:
    image: stevegore/icloudpd:latest
    container_name: icloudpd-kellesi
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      TZ: Australia/Sydney
    volumes:
      - /media/m2/photos/iphone/kellesi:/data
      - /home/steve/.pyicloud:/cookies
    command: icloudpd --directory /data --username ${ICLOUD_USERNAME} --watch-with-interval 3600 --cookie-directory /cookies

volumes:
  icloudpd_cookies:
