apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hermes.fullname" . }}-config
  labels:
    {{- include "hermes.labels" . | nindent 4 }}
data:
  HERMES_DASHBOARD: "true"
  HERMES_DASHBOARD_PORT: "9119"
  HERMES_DASHBOARD_INSECURE: {{ .Values.hermes.dashboardInsecure | quote }}
  TZ: {{ .Values.hermes.userTimezone | quote }}
