version: '3.5'

services:
  goldenboards:
    image: goldenboards  
    environment:
      TZ: Australia/Sydney
    restart: unless-stopped
    volumes:
      - /var/goldenboards:/var/goldenboards    
      - /etc/localtime:/etc/localtime:ro
    
