services:
  stirling-pdf:
    image: frooodle/s-pdf:latest@sha256:66b6edb8ee62e307a8b335166e8931a6e65b39c9bf73b5e517fbfe9c613ba221
    container_name: pdf-stirling-pdf-1
    restart: unless-stopped
    ports:
      - "8083:8080"
    environment:
      DOCKER_ENABLE_SECURITY: "false"
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "false"
      LANGS: en_GB
    volumes:
      - stirling-pdf-config:/configs

volumes:
  stirling-pdf-config:
