apiVersion: v1
kind: Service
metadata:
  name: {{ include "caddy.fullname" . }}
  labels:
    {{- include "caddy.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | default "Local" }}
  {{- end }}
  selector:
    {{- include "caddy.selectorLabels" . | nindent 4 }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
