{{- if .Values.vault.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "caddy.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: {{ .Values.vault.mount }}
  path: {{ .Values.vault.config.path }}
  destination:
    name: {{ .Values.vault.config.secretName }}
    create: true
  refreshAfter: {{ .Values.vault.refreshAfter }}
  vaultAuthRef: {{ include "caddy.fullname" . }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "caddy.fullname" . }}-s3
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: {{ .Values.vault.mount }}
  path: {{ .Values.vault.s3.path }}
  destination:
    name: {{ .Values.vault.s3.secretName }}
    create: true
  refreshAfter: {{ .Values.vault.refreshAfter }}
  vaultAuthRef: {{ include "caddy.fullname" . }}
{{- end }}
