#!/usr/bin/env bash
#
# Reads MySQL HeatWave admin password + endpoint from the TF outputs and
# publishes a Vault entry at kv/mysql/heatwave-admin that VSO / hand-rolled
# clients can consume.
#
# Runs locally — pulls the ORM-managed state via the standard tf-env.sh
# activate path, reads terraform outputs, writes to Vault, deactivates.
#
# Usage:
#   source scripts/vault-env.sh && vlogin
#   bash scripts/publish-mysql-creds.sh
#
# Idempotent: re-running overwrites the Vault entry with whatever's currently
# in TF state. Run again after a TF apply that changed mysql creds.

set -euo pipefail

for bin in terraform vault jq; do
  command -v "$bin" >/dev/null || { echo "missing: $bin" >&2; exit 1; }
done
[[ -n "${VAULT_TOKEN:-}" ]] || {
  echo "VAULT_TOKEN not set — run: source scripts/vault-env.sh && vlogin" >&2
  exit 1
}

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TF_DIR="$(cd "$SCRIPT_DIR/.." && pwd)/terraform"

echo "==> activating local backend"
source "$SCRIPT_DIR/tf-env.sh" >/dev/null

cd "$TF_DIR"
terraform init -reconfigure >/dev/null

USER=$(terraform output -raw mysql_admin_username)
PASS=$(terraform output -raw mysql_admin_password)
HOST=$(terraform output -raw mysql_endpoint_hostname)
IP=$(terraform output -raw mysql_endpoint_ip)

# DATABASE_URL form Vaultwarden expects.
DB_URL="mysql://${USER}:${PASS}@${HOST}:3306/vaultwarden"

vault kv put kv/mysql/heatwave-admin \
  username="$USER" \
  password="$PASS" \
  hostname="$HOST" \
  private_ip="$IP" \
  database_url="$DB_URL" \
  note="MySQL HeatWave Free admin creds. Generated by random_password resource in terraform/mysql.tf — re-run scripts/publish-mysql-creds.sh after any TF apply that changes them." >/dev/null

echo "==> wrote kv/mysql/heatwave-admin"
echo "    username:    $USER"
echo "    hostname:    $HOST  (private IP $IP)"
echo "    db url:      mysql://${USER}:***@${HOST}:3306/vaultwarden"

echo
echo "==> deactivating local backend"
cd "$SCRIPT_DIR/.."
bash "$SCRIPT_DIR/tf-env-off.sh"
