#!/usr/bin/env bash
#
# Pull the homelab-tf stack's state from OCI Resource Manager into a local
# file and configure a temporary local backend pointing at it. Result: fast
# local `terraform plan` runs against the ORM-managed state without round-
# tripping plan jobs through ORM.
#
# Usage:
#   source scripts/tf-env.sh
#   cd terraform && terraform init -reconfigure && terraform plan
#
# ORM is the source of truth — local can `plan`, never `apply`. If you push
# state from local (`terraform state push`) you bypass ORM's job history;
# don't do that for real apply, only for emergencies.
#
# Re-source any time you want a fresh state snapshot.

# Don't use `set -euo pipefail` — this script is meant to be SOURCED, and
# those options would leak into the user's interactive shell.

_tfenv_script_path() {
  if [ -n "${BASH_VERSION:-}" ]; then
    printf '%s' "${BASH_SOURCE[0]}"
  elif [ -n "${ZSH_VERSION:-}" ]; then
    # zsh's $0 is the sourced script's path when FUNCTION_ARGZERO is set
    # (default since 5.0.6). Fall back to $argv[0] for older zsh.
    printf '%s' "${(%):-%x}"
  else
    printf '%s' "$0"
  fi
}

_tfenv_main() {
  local script_path script_dir tf_dir
  script_path=$(_tfenv_script_path)
  script_dir=$(cd "$(dirname "$script_path")" && pwd) || { echo "tf-env: cannot locate script dir" >&2; return 1; }
  tf_dir="${HOMELAB_TF_DIR:-$(cd "$script_dir/.." && pwd)/terraform}"

  local stack_ocid="${HOMELAB_TF_STACK_OCID:-ocid1.ormstack.oc1.ap-sydney-1.amaaaaaaxbp2yoqaytua3d676bavg2kdjw6oud5srw7egs3iea7q7ppiydoq}"
  local state_file="${HOMELAB_TF_STATE_FILE:-$HOME/.cache/orm-state/homelab-tf.tfstate}"
  local backend_override="$tf_dir/backend_override.tf"

  local bin
  for bin in oci jq; do
    command -v "$bin" >/dev/null || { echo "tf-env: missing required binary: $bin" >&2; return 1; }
  done

  mkdir -p "$(dirname "$state_file")" || return 1

  echo "→ Pulling state from ORM stack $stack_ocid..."
  oci resource-manager stack get-stack-tf-state \
    --stack-id "$stack_ocid" \
    --file "$state_file" 2>/dev/null || { echo "tf-env: state pull failed" >&2; return 1; }

  # Materialize an override.tf that wires a local backend pointing at the pulled
  # file. Terraform auto-loads `*_override.tf` and lets it shadow other config —
  # safe and reversible (the override file is gitignored).
  cat > "$backend_override" <<EOF
# Auto-generated by scripts/tf-env.sh — do not edit, do not commit.
# Pulls ORM-managed state to a local snapshot for fast \`terraform plan\`.
terraform {
  backend "local" {
    path = "$state_file"
  }
}
EOF

  local n serial
  n=$(jq '.resources | length' "$state_file")
  serial=$(jq -r '.serial' "$state_file")
  echo "✓ Cached state at $state_file ($n resources, serial $serial)"
  echo "  Override:  $backend_override"
  echo "  Next:      cd $tf_dir && terraform init -reconfigure && terraform plan"
}

_tfenv_main
unset -f _tfenv_main _tfenv_script_path
