#!/usr/bin/env bash
#
# Pull the homelab-tf stack's state from OCI Resource Manager into a local
# file and configure a temporary local backend pointing at it. Result: fast
# local `terraform plan` runs against the ORM-managed state without round-
# tripping plan jobs through ORM.
#
# Usage:
#   source scripts/vault-env.sh && vlogin     # optional — only needed if you
#                                             # plan to consult Vault for the
#                                             # OCI stack OCID lookup.
#   source scripts/tf-env.sh
#   cd terraform && terraform init -reconfigure && terraform plan
#
# ORM is the source of truth — local can `plan`, never `apply`. If you push
# state from local (`terraform state push`) you bypass ORM's job history;
# don't do that for real apply, only for emergencies.

set -euo pipefail

STACK_OCID="${HOMELAB_TF_STACK_OCID:-ocid1.ormstack.oc1.ap-sydney-1.amaaaaaaxbp2yoqaytua3d676bavg2kdjw6oud5srw7egs3iea7q7ppiydoq}"
STATE_FILE="${HOMELAB_TF_STATE_FILE:-$HOME/.cache/orm-state/homelab-tf.tfstate}"
BACKEND_OVERRIDE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/terraform/backend_override.tf"

for bin in oci jq; do
  command -v "$bin" >/dev/null || { echo "Missing required binary: $bin" >&2; return 1 2>/dev/null || exit 1; }
done

mkdir -p "$(dirname "$STATE_FILE")"

echo "→ Pulling state from ORM stack $STACK_OCID..."
oci resource-manager stack get-stack-tf-state --stack-id "$STACK_OCID" --file "$STATE_FILE" 2>/dev/null

# Materialize an override.tf that wires a local backend pointing at the pulled
# file. Terraform auto-loads `*_override.tf` and lets it shadow other config —
# safe and reversible (the override file is gitignored).
cat > "$BACKEND_OVERRIDE" <<EOF
# Auto-generated by scripts/tf-env.sh — do not edit, do not commit.
# Pulls ORM-managed state to a local snapshot for fast \`terraform plan\`.
terraform {
  backend "local" {
    path = "$STATE_FILE"
  }
}
EOF

n=$(jq '.resources | length' "$STATE_FILE")
serial=$(jq -r '.serial' "$STATE_FILE")
echo "✓ Cached state at $STATE_FILE ($n resources, serial $serial)"
echo "  Next: cd terraform && terraform init -reconfigure && terraform plan"
