apiVersion: v1
kind: Service
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "vaultwarden.selectorLabels" . | nindent 4 }}
  ports:
    - name: web
      port: {{ .Values.service.webPort }}
      targetPort: web
      protocol: TCP
    - name: websocket
      port: {{ .Values.service.websocketPort }}
      targetPort: websocket
      protocol: TCP
