apiVersion: v2
name: vault
description: HashiCorp Vault with OCI KMS auto-unseal and Object Storage backend
type: application
version: 1.0.0
appVersion: "1.18.1"

dependencies:
  - name: vault
    version: 0.28.1
    repository: https://helm.releases.hashicorp.com
