apiVersion: v2
name: vault
description: HashiCorp Vault with OCI KMS auto-unseal and Object Storage backend
type: application
version: 1.0.0
appVersion: "2.0.3"

dependencies:
  - name: vault
    version: 0.34.0
    repository: https://helm.releases.hashicorp.com
