apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: {{ .Values.argocd.url | quote }}
  # Disable local admin account (use GitHub SSO only)
  admin.enabled: "false"
  # Skip TLS verification for internal Dex communication (Caddy handles external TLS)
  oidc.tls.insecure.skip.verify: "true"
  # OIDC configuration - enables auto-redirect to SSO
  oidc.config: |
    name: GitHub
    issuer: {{ .Values.argocd.url }}/api/dex
    clientID: argo-cd
    requestedScopes: ["openid", "profile", "email"]
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: {{ .Values.github.clientID | quote }}
          clientSecret: $dex.github.clientSecret
          # Use GitHub username as the user ID instead of numeric ID
          useLoginAsID: true
