apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: {{ .Values.argocd.url | quote }}
  # Skip TLS verification for internal Dex communication (Caddy handles external TLS)
  oidc.tls.insecure.skip.verify: "true"
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: {{ .Values.github.clientID | quote }}
          clientSecret: $dex.github.clientSecret
          # Use GitHub username as the user ID instead of numeric ID
          useLoginAsID: true
